import os
import subprocess
import sys


def _ensure_requirements_installed():
    """
    在首次加载节点时自动安装依赖。
    若 requirements.txt 或 pip 执行失败，仅打印警告，继续加载，避免阻断 ComfyUI。
    可以通过环境变量 COMFYUI_MYAPI_SKIP_AUTO_INSTALL=1 跳过自动安装。
    """
    if os.environ.get("COMFYUI_MYAPI_SKIP_AUTO_INSTALL") == "1":
        print("[Comfyui-MyApi] 跳过依赖自动安装（检测到环境变量 COMFYUI_MYAPI_SKIP_AUTO_INSTALL=1）")
        return

    base_dir = os.path.dirname(os.path.realpath(__file__))
    requirements_path = os.path.join(base_dir, "requirements.txt")
    marker_path = os.path.join(base_dir, ".requirements_installed")

    if not os.path.exists(requirements_path):
        return

    if os.path.exists(marker_path):
        return

    try:
        print("[Comfyui-MyApi] 正在自动安装依赖...")
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-r", requirements_path]
        )
        with open(marker_path, "w", encoding="utf-8") as marker:
            marker.write("installed")
        print("[Comfyui-MyApi] 依赖安装完成。")
    except Exception as exc:
        print(f"[Comfyui-MyApi] 自动安装依赖失败：{exc}")
        print("请手动执行：pip install -r requirements.txt")


_ensure_requirements_installed()

from .bizyair_nanobanana_node import NODE_CLASS_MAPPINGS as NANOBANANA_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NANOBANANA_NODE_DISPLAY_NAME_MAPPINGS
from .bizyair_seedream4_node import NODE_CLASS_MAPPINGS as SEEDREAM4_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SEEDREAM4_NODE_DISPLAY_NAME_MAPPINGS
from .bizyair_gemini3flash_node import NODE_CLASS_MAPPINGS as GEMINI3FLASH_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GEMINI3FLASH_NODE_DISPLAY_NAME_MAPPINGS
from .deepseek_v32_exp_node import NODE_CLASS_MAPPINGS as DEEPSEEK_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DEEPSEEK_NODE_DISPLAY_NAME_MAPPINGS
from .doubao_node import NODE_CLASS_MAPPINGS as DOUBAO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DOUBAO_NODE_DISPLAY_NAME_MAPPINGS
from .doubao_seedream45_node import NODE_CLASS_MAPPINGS as DOUBAO_SEEDREAM45_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DOUBAO_SEEDREAM45_NODE_DISPLAY_NAME_MAPPINGS
from .doubao_seed_translation_node import NODE_CLASS_MAPPINGS as DOUBAO_SEED_TRANSLATION_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DOUBAO_SEED_TRANSLATION_NODE_DISPLAY_NAME_MAPPINGS
from .gemini_image_preview_node import NODE_CLASS_MAPPINGS as GEMINI_IMAGE_PREVIEW_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GEMINI_IMAGE_PREVIEW_NODE_DISPLAY_NAME_MAPPINGS
from .gemini_node import NODE_CLASS_MAPPINGS as GEMINI_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GEMINI_NODE_DISPLAY_NAME_MAPPINGS
from .qwen_node import NODE_CLASS_MAPPINGS as QWEN_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_NODE_DISPLAY_NAME_MAPPINGS
from .qwen_image_edit_plus_node import NODE_CLASS_MAPPINGS as QWEN_IMAGE_EDIT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_IMAGE_EDIT_NODE_DISPLAY_NAME_MAPPINGS
from .xai_node import NODE_CLASS_MAPPINGS as XAI_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as XAI_NODE_DISPLAY_NAME_MAPPINGS
from .text_segmentation_node import NODE_CLASS_MAPPINGS as TEXT_SEGMENTATION_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_SEGMENTATION_NODE_DISPLAY_NAME_MAPPINGS
# 合并所有节点映射（按类别分组排序）
NODE_CLASS_MAPPINGS = {}
# BizyAir 系列
NODE_CLASS_MAPPINGS.update(NANOBANANA_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SEEDREAM4_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GEMINI3FLASH_NODE_CLASS_MAPPINGS)
# DeepSeek 系列
NODE_CLASS_MAPPINGS.update(DEEPSEEK_NODE_CLASS_MAPPINGS)
# 豆包系列
NODE_CLASS_MAPPINGS.update(DOUBAO_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DOUBAO_SEEDREAM45_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DOUBAO_SEED_TRANSLATION_NODE_CLASS_MAPPINGS)
# Gemini 系列
NODE_CLASS_MAPPINGS.update(GEMINI_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GEMINI_IMAGE_PREVIEW_NODE_CLASS_MAPPINGS)
# Qwen 系列
NODE_CLASS_MAPPINGS.update(QWEN_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(QWEN_IMAGE_EDIT_NODE_CLASS_MAPPINGS)
# XAI 系列
NODE_CLASS_MAPPINGS.update(XAI_NODE_CLASS_MAPPINGS)
# 文本处理系列
NODE_CLASS_MAPPINGS.update(TEXT_SEGMENTATION_NODE_CLASS_MAPPINGS)

# 初始化显示名称映射并合并（按类别分组排序）
NODE_DISPLAY_NAME_MAPPINGS = {}
# BizyAir 系列
NODE_DISPLAY_NAME_MAPPINGS.update(NANOBANANA_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SEEDREAM4_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GEMINI3FLASH_NODE_DISPLAY_NAME_MAPPINGS)
# DeepSeek 系列
NODE_DISPLAY_NAME_MAPPINGS.update(DEEPSEEK_NODE_DISPLAY_NAME_MAPPINGS)
# 豆包系列
NODE_DISPLAY_NAME_MAPPINGS.update(DOUBAO_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DOUBAO_SEEDREAM45_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DOUBAO_SEED_TRANSLATION_NODE_DISPLAY_NAME_MAPPINGS)
# Gemini 系列
NODE_DISPLAY_NAME_MAPPINGS.update(GEMINI_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GEMINI_IMAGE_PREVIEW_NODE_DISPLAY_NAME_MAPPINGS)
# Qwen 系列
NODE_DISPLAY_NAME_MAPPINGS.update(QWEN_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(QWEN_IMAGE_EDIT_NODE_DISPLAY_NAME_MAPPINGS)
# XAI 系列
NODE_DISPLAY_NAME_MAPPINGS.update(XAI_NODE_DISPLAY_NAME_MAPPINGS)
# 文本处理系列
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_SEGMENTATION_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS'] 