from .qwen_node import NODE_CLASS_MAPPINGS as QWEN_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWEN_NODE_DISPLAY_NAME_MAPPINGS
from .doubao_node import NODE_CLASS_MAPPINGS as DOUBAO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DOUBAO_NODE_DISPLAY_NAME_MAPPINGS
from .xai_node import NODE_CLASS_MAPPINGS as XAI_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as XAI_NODE_DISPLAY_NAME_MAPPINGS
from .gemini_node import NODE_CLASS_MAPPINGS as GEMINI_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GEMINI_NODE_DISPLAY_NAME_MAPPINGS
# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(QWEN_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(XAI_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DOUBAO_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(GEMINI_NODE_CLASS_MAPPINGS)

# 初始化显示名称映射并合并
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(QWEN_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(XAI_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DOUBAO_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GEMINI_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS'] 